exclude: ^tests/data/(expected/.+|setup.py)$

repos:
  ###################
  #    FORMATTER    #
  ###################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "0.13.0"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/python/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.3.2"]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
      - id: setup-cfg-fmt
        args: [--include-version-classifiers]

  ###################
  #     LINTER      #
  ###################
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        exclude: "docs"
        additional_dependencies: ["pydantic>2"]

  ###################
  #   LINTER DOCS   #
  ###################
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        alias: pydoclint
        args:
          - "--select=DOC"
          - "--extend-ignore=DOC502"
          - "--color=always"
          - "--require-return-section-when-returning-none=False"
          - "--allow-init-docstring=True"
          - "--skip-checking-short-docstrings=False"
          - "--count"
        name: "pydoclint"
        exclude: "^(docs/|setup.py$|tests?/)"
        additional_dependencies: [pydoclint==0.1.5]

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: [-v, --config=pyproject.toml, "qt_dev_helper"]
        pass_filenames: false

  - repo: https://github.com/myint/rstcheck
    rev: "v6.2.4"
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        exclude: "docs/_templates"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types: [file]
        types_or: [python, pyi, markdown, rst, jupyter]
        args: [-L nnumber]

  - repo: https://github.com/rhysd/actionlint
    rev: "v1.6.25"
    hooks:
      - id: actionlint
