exclude: ^tests/data/(expected/.+|setup.py)$

repos:
  ###################
  #    FORMATTER    #
  ###################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4 # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt
        args: [--include-version-classifiers]

  ###################
  #     LINTER      #
  ###################
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: "docs"
        additional_dependencies: ["types-all", "pydantic"]

  ###################
  #   LINTER DOCS   #
  ###################
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: "^docs|tests|setup.py"

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
        exclude: "^docs|tests|setup.py|qt_dev_helper/cli"

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [-v, --config=pyproject.toml, "qt_dev_helper"]
        pass_filenames: false

  - repo: https://github.com/myint/rstcheck
    rev: "v6.1.1"
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        exclude: "docs/_templates"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        types: [file]
        types_or: [python, pyi, markdown, rst, jupyter]
        args: [-L nnumber]
