name: "Tests"
on:
  push:
    tags:
      - v**
    branches-ignore:
      - "dependabot/**"
      - "sourcery/**"
      - "create-pr-action/**"
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -U -r docs/requirements.txt
          pip install .
      - name: Show installed dependencies
        run: |
          pip freeze
      - name: Build docs
        run: make --directory=docs clean html

  docs-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -U -q -r docs/requirements.txt
          pip install .
      - name: Show installed dependencies
        continue-on-error: true
        run: |
          pip freeze
      - name: Build docs
        run: make --directory=docs clean linkcheck

  test:
    runs-on: ${{ matrix.os }}
    needs: [pre-commit, docs]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        # macOS-latest runs on M1 hardware, so we are using macos-12,
        # the last version supporting Intel hardware, to ensure compatibility.
        # exclude:
        #   - os: macOS-latest
        #     python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install -U .
          python -m pip install -r requirements_dev.txt
      - name: Run tests
        run: |
          pytest --cov=./ --cov-report term --cov-report xml --cov-config=pyproject.toml tests
      - name: Codecov Upload
        continue-on-error: true
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          name: ${{ matrix.os }}-py${{ matrix.python-version }}

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
      - name: Build dist
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
